# Site settings
title: "My Portfolio"
description: "Welcome to my portfolio site."
url: "https://manojskulkarni2003.github.io/manojaps.github.io/" # the base hostname & protocol for your site

# Author settings
author:
  name: "MANOJ SHANKAR KULKARNI"
  email: "manojskulkarni2003@gmail.com"
  twitter_username: your-twitter-username
  github_username: your-github-username

# Jekyll settings
theme: jekyll-theme-architect

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude these files from the final build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Social links
social_links:
  - name: "GitHub"
    url: "https://github.com/your-github-username"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/your-linkedin-username/"
  - name: "Twitter"
    url: "https://twitter.com/your-twitter-username"

# Google Analytics (optional)
google_analytics: UA-XXXXXXXX-X

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Custom navigation links
navigation:
  - text: "Home"
    url: "/"
  - text: "About"
    url: "/about/"
  - text: "Projects"
    url: "/projects/"
  - text: "Contact"
    url: "/contact/"

# Custom variables (optional)
custom_var: "Custom value"

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      author: "Your Name"
